server:
  port: 8081
spring:
  datasource:
    account:
      url: jdbc:mysql://10.8.97.200:3306/tl1?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
    storage:
      url: jdbc:mysql://10.8.97.200:3306/tl2?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    pool:
      max-total: 80
      max-active: 80
      max-wait: -1
      max-idle: 80
      min-idle: 0